## Лабораторная работа 1.

## Знакомство с библиотеками для анализа данных: numpy, scipy, matplotlib

Первая часть - знакомство с numpy. Перед выполнением заданий ознакомьтесь с документацией(http://www.numpy.org)

Решение каждой задачи подразумевает написание функции на языке Python, а так же примеры работы это функции. 
При реализации нужно использовать методы из библиотеки. Рекомендуется выполнить все задания по минимуму используя циклы. 

Под матрицей в заданиях понимается двумерный [numpy.array](https://docs.scipy.org/doc/numpy/reference/generated/numpy.array.html)

Для подключения модуля воспользуйтесь следующей строкой. Используйте стандартное сокращение np.

In [4]:
import numpy as np

Пример создания одномерного и двумерного массивов методами numpy 

In [5]:
X1d = np.array([1, 2, 3], dtype=np.float64)
print(X1d)

[1. 2. 3.]


In [6]:
X2d = np.array([[1, 2],
                [3, 4]], dtype=np.float)
print(X2d)

[[1. 2.]
 [3. 4.]]


** Задача 1. ** Напишите функцию принимающую на вход 3 массива - ```A```, ```B```, ```C```. Функция должна возвращать ** True ** - если они равны и ** False ** иначе. Рекомендуется ** не ** использовать оператор ==.

In [10]:
def is_equal(A, B, C):
    return np.array_equal(A, B) and np.array_equal(B, C)

 ** Задание 2. ** Реализуйте функцию, принимающую на вход матрицу ```X``` и некоторое число ```a``` и возвращающую ближайший к числу элемент матрицы.

Например, для ```X = np.arange(0,20).reshape((4, 5))``` и ```a = 7.7``` ответом будет 8.

In [33]:
def near_val(X, a):
    return min(map(lambda x: x - a, X.flatten()), key=abs) + a

print(near_val(np.arange(-8.5, 3.5).reshape(2, 6), 0.1))

0.5


** Задача 3. ** Напишите функцию принимающую вектор строку и возвращающую вектор столбец. В этом задании **запрещается** пользоваться операцией транспонирования и рекомедуется воспользоваться методом [reshape](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.reshape.html).

In [46]:
def rot_vec(x):
    return np.reshape(x, (len(x), 1))

print(rot_vec(np.arange(6)))

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]


** Задача 4. ** Напишите функцию принимающую на вход двумерный массив, а возвращающую массив с диагональными элементами этой матрицы. Пример: ```[[1, 2], [3, 4]] -> [1 4]```

In [48]:
def get_diag(X):
    return X.diagonal()

print(get_diag(np.array([[1,2], [3,4]])))

[1 4]


** Задача 5. ** Найдите среденее значение всех не нулевых элементов стоящих на главной диагонали матрицы. 

In [53]:
def mean_diag(X):
    return np.mean(filter(lambda x: x != 0, X.diagonal()))

print(mean_diag(np.arange(9).reshape(3, 3)))

6.0


** Задача 6. ** Напишите функцию принимающую на вход двумерный массив, а возвращающую массив элементов находящихся на второстепенной диагонали. Пример: ```[[1, 2], [3, 4]] -> [2 3]```

In [61]:
def sec_diag(X):
    return np.fliplr(X).diagonal()

print(sec_diag(np.arange(9).reshape(3, 3)))

[2 4 6]


** Задача 7. ** Функци принимает двумерный квадратный массив. Найдите [след матрицы](https://ru.wikipedia.org/wiki/След_матрицы). Используйте ** только ** функции из numpy!

In [63]:
def tr(X):
    return X.diagonal().sum()

print(tr(np.arange(4).reshape(2, 2)))

3


** Задача 8. ** На вход вы получаете массив чисел. Функция должна вернуть матрицу состоящую из элементов данного массива, размером максимально приближенным к квадрату. Возможно Вам понадобятся циклы. 

Пример ```[1, 2, 3, 4] -> [[1, 2], [3, 4]]```

In [17]:
def make_sq(A):
    pass

** Задача 9. **Реализуйте функцию, принимающую на вход матрицу ```X```. Удалите из неё все дубликаты строчек. 

Пример ```[[1 0], [0 1], [1 0]] -> [[1 0], [0 1]] ```

In [ ]:
def del_dublicates(X):
    pass

** Задача 10. ** Реализуйте функцию, принимающую на вход вектор ```X```.  Вставьте между всеми числами число 42.0

Пример ```[1, 2, 3, 4, 5] -> [1, 42, 2, 42, 3, 42, 4, 42, 5]```

In [ ]:
def insert_42(X):
    pass